version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker_volumes/my-db:/var/lib/mysql
    stdin_open: true
    tty: true

  php_apache: 
    image: php:7.3-apache
    container_name: apache
    volumes:
      - ./docker_volumes/php/:/var/www/html/
    environment:
      - APACHE_PORT
    ports:
      - ${APACHE_PORT}:80
    networks: 
      - apache_mysql_network
    stdin_open: true
    tty: true
  
volumes:
  my-db:

networks:
  apache_mysql_network:
    driver: bridge